# neims_output_to_mgf configuration  –  gecko TMS-derivatized molecules
# Run with:  python neims_output_to_mgf.py config_gecko_tms.yaml

spectra_dir: data/neims/gecko_EIMS_spectra/gecko/NEIMS/derivatized  # directory containing the NEIMS output folders e.g. "000000"
smiles_csv:  data/neims/gecko_EIMS_spectra/TMS/SMILES_gecko_TMS_corr_nitrate.csv # CSV file containing the SMILES strings
output:      data/neims/gecko_EIMS_spectra/mist_inputs/gecko_tms_spectra.mgf # output MGF file

smiles_col: Modified_SMILES   # derivatized CSV has Original_SMILES + Modified_SMILES
id_prefix:  gecko_tms
min_peaks:  5
log_level:  INFO
